name: Main

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        dotnet-quality: 'ga'
    - name: Build
      run: dotnet build -c Release "src/Hedgehog.Xunit"
    - name: Test
      run: dotnet test -c Release "tests/Hedgehog.Xunit.Tests" /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        path-to-lcov: tests/Hedgehog.Xunit.Tests/TestResults/coverage.info
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: "src/Hedgehog.Xunit/Hedgehog.Xunit.fsproj"
        PACKAGE_NAME: "Hedgehog.Xunit"
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
